notifications:
  email:
    on_success: change
    on_failure: always
language: python
sudo: true
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
before_install:
  - sudo apt-get install curl autoconf automake libtool python-dev pkg-config
  - git clone https://github.com/openvenues/libpostal
  - cd libpostal
  - ./bootstrap.sh
  - ./configure --datadir=/tmp
  - sudo make
  - sudo make install
  - sudo ldconfig
  - cd ..
install:
  - pip install -e .
script:
  - nosetests postal/tests
